FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./

COPY apps/chatbot_ui ./apps/chatbot_ui

ENV UV_COMPILE_BYTECODE=1

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --package chatbot_ui

ENV PYTHONOPTIMIZE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/apps/chatbot_ui/src:$PYTHONPATH"

RUN addgroup --system app && \
adduser --system --ingroup app app && \
chown -R app:app /app && \
mkdir -p /home/app && \
chown -R app:app /home/app && \
mkdir -p /home/app/.streamlit && \
mkdir -p /home/app/.streamlit/data && \
mkdir -p /home/app/.streamlit/cache && \
chown -R app:app /home/app/.streamlit

ENV HOME=/home/app

USER app

EXPOSE 8501

WORKDIR /app/apps/chatbot_ui/src

CMD [ "streamlit", "run", "chatbot_ui/app.py", "--server.address=0.0.0.0"]